import Head from 'next/head'
import Main from '../components/Main'
import Button from '../components/Button'
import ColorSwatch from '../components/ColorSwatch'
import { useColorSwatches } from '../app/hooks'

export default function Home() {
  const { data: colorObjs, refetch: generateColors } = useColorSwatches()

  return (
    <div>
      <Head>
        <title>Color Swatches</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Main>
        <h1>Color swatch generator</h1>
        <div>{colorObjs && <ColorSwatch colorObjs={colorObjs} />}</div>

        <Button onClick={generateColors}>Generate</Button>
      </Main>
    </div>
  )
}
